# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-05 23:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0016_auto_20160608_1535'),
        ('filer', '0006_auto_20160623_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPluginModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_publication', models.DateField()),
                ('published', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True)),
                ('detail', djangocms_text_ckeditor.fields.HTMLField(blank=True, null=True)),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.Image')),
            ],
            options={
                'ordering': ('-date_publication',),
                'verbose_name': 'New',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='NewsPluginModel',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_news_newspluginmodel', serialize=False, to='cms.CMSPlugin')),
                ('number', models.IntegerField(default=0)),
                ('template', models.CharField(choices=[('djangocms_news/mosaic.html', 'Mosaico')], max_length=255, verbose_name='Template')),
                ('columns', models.IntegerField(choices=[(2, 'Dos columnas'), (3, 'Tres columnas')], default=1)),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
